
// BOT
// loading
export const REQUEST_BOT_TEMPLATES = "REQUEST_BOT_TEMPLATES";
export const SUCCESS_BOT_TEMPLATES = "SUCCESS_BOT_TEMPLATES";
export const FAILURE_BOT_TEMPLATES = "FAILURE_BOT_TEMPLATES";
// make
export const REQUEST_MAKE_NEW_TEMPLATE = "REQUEST_MAKE_NEW_TEMPLATE";
export const SUCCESS_MAKE_NEW_TEMPLATE = "SUCCESS_MAKE_NEW_TEMPLATE";
export const FAILURE_MAKE_NEW_TEMPLATE = "FAILURE_MAKE_NEW_TEMPLATE";
// update
export const REQUEST_UPDATE_TEMPLATE = "REQUEST_UPDATE_TEMPLATE";
export const SUCCESS_UPDATE_TEMPLATE = "SUCCESS_UPDATE_TEMPLATE";
export const FAILURE_UPDATE_TEMPLATE = "FAILURE_UPDATE_TEMPLATE";
// delete
export const REQUEST_DELETE_TEMPLATE = "REQUEST_DELETE_TEMPLATE";
export const SUCCESS_DELETE_TEMPLATE = "SUCCESS_DELETE_TEMPLATE";
export const FAILURE_DELETE_TEMPLATE = "FAILURE_DELETE_TEMPLATE";


// USER
// loading
export const REQUEST_LOAD_USER = "REQUEST_LOAD_USER";
export const SUCCESS_LOAD_USER = "SUCCESS_LOAD_USER";
export const FAILURE_LOAD_USER = "FAILURE_LOAD_USER";
// login
export const REQUEST_AUTH_LOGIN = "REQUEST_AUTH_LOGIN";
export const SUCCESS_AUTH_LOGIN = "SUCCESS_AUTH_LOGIN";
export const FAILURE_AUTH_LOGIN = "FAILURE_AUTH_LOGIN";

